services:
  mysql:
    platform: linux/x86_64
    image: 'mysql:8.0-debian'
    container_name: ems-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'ems'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'root'
    ports:
      - "0.0.0.0:8306:3306"
    volumes:
      - './build/docker-volumes/ems_mysql:/var/lib/mysql'
